[package]
name = "stardb-exporter"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
arboard = "3.4.0"
base64 = "0.22.1"
pcap = "2.0.0"
reliquary = { git = "https://github.com/juliuskreutz/reliquary" }
self_update = "0.40.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
ureq = { version = "2.9.7", features = ["json"] }
