[package]
name = "stardb-exporter"
version = "1.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
arboard = "3.4.0"
base64 = "0.22.1"
pcap = "2.0.0"
reliquary = { git = "https://github.com/juliuskreutz/reliquary" }
self_update = { version = "0.40.0", features = [
    "archive-zip",
    "compression-zip-deflate",
] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
