[package]
name = "stardb-exporter"
version = "2.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
arboard = "3.4.1"
artifactarium = { git = "https://github.com/hashblen/artifactarium" }
base64 = "0.22.1"
eframe = { version = "0.29.0", default-features = false, features = [
    "default_fonts",
    "glow",
] }
egui = "0.29.0"
pcap = "2.2.0"
reliquary = { git = "https://github.com/juliuskreutz/reliquary" }
self_update = { version = "0.41.0", features = [
    "archive-zip",
    "compression-zip-deflate",
] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
ureq = { version = "2.10.1", features = ["json"] }
