name: Clippy

on: push

jobs:
  clippy-windows:
    name: Clippy Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Npcap Sdk
        run: |
          curl https://npcap.com/dist/npcap-sdk-1.13.zip -o sdk.zip
          unzip sdk.zip

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Patch
        run: python patch.py

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
        env:
          LIB: ${{ github.workspace }}/Lib/x64/

  clippy-linux:
    name: Clippy Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Patch
        run: python patch.py

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  clippy-macos:
    name: Clippy Macos
    runs-on: macos-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Patch
        run: python patch.py

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
