name: Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Get Npcap Sdk
        run: |
          curl https://npcap.com/dist/npcap-sdk-1.13.zip -o sdk.zip
          unzip sdk.zip

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
        env:
          LIB: ${{ github.workspace }}/Lib/x64/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: target/release/stardb-exporter.exe

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install libpcap
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: target/release/stardb-exporter

  build-macos:
    name: Build Macos
    runs-on: macos-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install libpcap
        run: brew update && brew install libpcap

      - name: Get Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos
          path: target/release/stardb-exporter

  release:
    name: Release
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Rename
        run: |
          mv windows/stardb-exporter.exe stardb-exporter.exe
          mv linux/stardb-exporter stardb-exporter-linux
          mv macos/stardb-exporter stardb-exporter-macos

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 1.0.0
          prerelease: false
          title: Latest Release
          files: |
            stardb-exporter.exe
            stardb-exporter-linux
            stardb-exporter-macos
